# Generated by Django 3.2.4 on 2021-07-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gig', '0003_alter_tutiongig_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GigOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gig.tutiongig')),
                ('order_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackorder.orderstatus')),
            ],
        ),
    ]
