# Generated by Django 3.2.4 on 2021-07-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_totalinstructor'),
        ('trackorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutionSubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackorder.orderstatus')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructor.tutionsubscription')),
            ],
        ),
    ]
