# Generated by Django 3.2.4 on 2021-07-06 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutionGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('pph', models.BigIntegerField()),
                ('description', models.TextField(max_length=100000)),
                ('thumbnail', models.ImageField(upload_to='gig_thumbnail')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.classtype')),
            ],
        ),
    ]
