# Generated by Django 3.2.4 on 2021-07-06 22:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutiongig',
            name='description',
            field=tinymce.models.HTMLField(max_length=100000),
        ),
    ]
