# Generated by Django 3.2.4 on 2021-07-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_subject'),
        ('gig', '0002_alter_tutiongig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutiongig',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
    ]
