# Generated by Django 2.2.13 on 2021-07-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_alter_tutiongig_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutiongig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
