# Generated by Django 3.2.4 on 2021-07-07 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.BigIntegerField()),
                ('description', tinymce.models.HTMLField(max_length=100000)),
                ('thumbnail', models.ImageField(upload_to='gig_thumbnail')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.classtype')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
                ('subscription_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructor.subscriptiontype')),
            ],
        ),
    ]
