# Generated by Django 3.2.4 on 2021-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_instructorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='dp',
            field=models.ImageField(upload_to='instructor_dp'),
        ),
    ]
