# Generated by Django 3.2.4 on 2021-07-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_rename_student_instructorprofile_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
            ],
        ),
    ]
