# Generated by Django 3.2.4 on 2021-07-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
            ],
        ),
    ]
